name: drift_generation_issue
sdkPath: .fvm/flutter_sdk
packages:
  - features/**
  - .
ide:
  intellij: true

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  build_runner:build:
    run: |
      melos exec --concurrency=1 --fail-fast --depends-on="build_runner" -- \
        "dart pub run build_runner build --delete-conflicting-outputs"