name: db
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  drift: 2.11.1
  sqlite3: ^2.1.0
  sqlcipher_flutter_libs: ^0.5.7

  feature_a:
    path: ../feature_a

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  drift_dev: 2.11.2